bounties:
  items:
#   List of items that can be requested
    requested:
      item1:
        material: IRON_INGOT
        amount: 6
        slot: 1
        reward:
          material: DIRT
          amount: 3

      item2:
        material: GOLD_INGOT
        amount: 6
        slot: 2
        reward:
          material: STONE
          amount: 2

#   List of items that can be used as a reward
  menu:
    title: "[Bounties]"