bounties:
  items:
    requested:
#############################################
#   Example Item:
#      item1:     <- Item name. Cannot be repeated in config
#        enabled: true     <- If true, item is enabled
#        removable: true      <- Defines if after redeeming offer gets removed
#        material: IRON_INGOT       <- ID of item that is needed to redeem prize
#        amount: 6        <- Amount of required item
#        reward:
#          material: DIRT       <- ID of prize item
#          amount: 3          <- Amount of prize reward
#############################################
      item1:
        enabled: true
        removable: true
        material: IRON_INGOT
        amount: 6
        reward:
          material: DIRT
          amount: 3

      item2:
        enabled: true
        removable: false
        material: GOLD_INGOT
        amount: 6
        reward:
          material: STONE
          amount: 2

#   List of items that can be used as a reward
  menu:
    title: "[Bounties]"




















# =======================================

#   DO NOT CHANGE ANYTHING BELOW THIS LINE

# =======================================
  data:
    item1:
      material: STONE
      amount: 2
      user: pmalys
