name: Bounties
version: '${project.version}'
main: bettermobs.bounties.Bounties
api-version: 1.19
authors: [ bettermobs ]
description: This plugin adds bounties system
website: https://discord.gg/Y9BbesGwXa
commands:
  boinfo:
    description: Show info
    permission: bounties.info
    usage: /<command>
  boopen:
    description: Open bounties menu
    permission: bounties.open
    usage: /<command>
  boreload:
    description: Reloads config
    permission: bounties.reload
    usage: /<command>
  boadd:
    description: Adds held item to bounty system
    permission: bounties.add
    usage: /<command>
  botake:
    description: Adds traded items to your inventory
    permission: bounties.take
    usage: /<command>