name: Bounties
version: '${project.version}'
main: bettermobs.bounties.Bounties
api-version: 1.19
authors: [ bettermobs ]
description: Plugin that adds bounties for making certain quests
website: https://discord.gg/Y9BbesGwXa
